// Package model contains the types for schema 'db_ccwork'.
package model

// Code generated by xo. DO NOT EDIT.
import (
	"strings"
)
// TUser represents a row from 'db_ccwork.t_user'.
type TUser struct {
        ID uint `json:"id"`
        UserID uint64 `json:"user_id"`
        UserAccount string `json:"user_account"`
        UserName string `json:"user_name"`
        EnName string `json:"en_name"`
        Gender int8 `json:"gender"`
        Sign string `json:"sign"`
        Email string `json:"email"`
        Avatar string `json:"avatar"`
        Pwd string `json:"pwd"`
        Birth uint `json:"birth"`
        Tel string `json:"tel"`
        UserDesc string `json:"user_desc"`
        Mobile string `json:"mobile"`
        UserStatus int `json:"user_status"`
        Nation string `json:"nation"`
        Province string `json:"province"`
        City string `json:"city"`
        County string `json:"county"`
        Address string `json:"address"`
        InitFlag int8 `json:"init_flag"`
        ShowMask uint `json:"show_mask"`
        FieldShowControl string `json:"field_show_control"`
        Label uint `json:"label"`
        CanbeChat int8 `json:"canbe_chat"`
        DutyID uint64 `json:"duty_id"`
        SecretLevel uint `json:"secret_level"`
        CreatedTime uint `json:"created_time"`
        UpdatedTime uint `json:"updated_time"`
        UserSource string `json:"user_source"`
}

// TUserColumns defines and stores column names for 'db_ccwork.t_user'.
type TUserColumns struct {
    ID string
    UserID string
    UserAccount string
    UserName string
    EnName string
    Gender string
    Sign string
    Email string
    Avatar string
    Pwd string
    Birth string
    Tel string
    UserDesc string
    Mobile string
    UserStatus string
    Nation string
    Province string
    City string
    County string
    Address string
    InitFlag string
    ShowMask string
    FieldShowControl string
    Label string
    CanbeChat string
    DutyID string
    SecretLevel string
    CreatedTime string
    UpdatedTime string
    UserSource string
}

// GetTUserTableName returns the database table name for TUser.
func GetTUserTableName() string {
    return "t_user"
}

// GetTUserFieldString returns all column names as a comma-separated string (for SELECT).
func GetTUserFieldString () string {
    return `id, user_id, user_account, user_name, en_name, gender, sign, email, avatar, pwd, birth, tel, user_desc, mobile, user_status, nation, province, city, county, address, init_flag, show_mask, field_show_control, label, canbe_chat, duty_id, secret_level, created_time, updated_time, user_source`
}

// GetTUserFieldStringSlice returns insert column names as a string slice (excludes auto-increment primary key).
func GetTUserFieldStringSlice () []string {
    return strings.Split(`user_id, user_account, user_name, en_name, gender, sign, email, avatar, pwd, birth, tel, user_desc, mobile, user_status, nation, province, city, county, address, init_flag, show_mask, field_show_control, label, canbe_chat, duty_id, secret_level, created_time, updated_time, user_source`,",")
}

// GetTUserAddField returns the field values of tu as a slice for INSERT operations.
func GetTUserAddField ( tu  *TUser) []interface{} {
    return [] interface{} {
                            tu.UserID,
                            tu.UserAccount,
                            tu.UserName,
                            tu.EnName,
                            tu.Gender,
                            tu.Sign,
                            tu.Email,
                            tu.Avatar,
                            tu.Pwd,
                            tu.Birth,
                            tu.Tel,
                            tu.UserDesc,
                            tu.Mobile,
                            tu.UserStatus,
                            tu.Nation,
                            tu.Province,
                            tu.City,
                            tu.County,
                            tu.Address,
                            tu.InitFlag,
                            tu.ShowMask,
                            tu.FieldShowControl,
                            tu.Label,
                            tu.CanbeChat,
                            tu.DutyID,
                            tu.SecretLevel,
                            tu.CreatedTime,
                            tu.UpdatedTime,
                            tu.UserSource,
            }
}

// GetTUserScanField returns pointers to all fields of tu for use with rows.Scan().
func GetTUserScanField ( tu  *TUser) []interface{} {
    return [] interface{} {
                    &tu.ID,
                    &tu.UserID,
                    &tu.UserAccount,
                    &tu.UserName,
                    &tu.EnName,
                    &tu.Gender,
                    &tu.Sign,
                    &tu.Email,
                    &tu.Avatar,
                    &tu.Pwd,
                    &tu.Birth,
                    &tu.Tel,
                    &tu.UserDesc,
                    &tu.Mobile,
                    &tu.UserStatus,
                    &tu.Nation,
                    &tu.Province,
                    &tu.City,
                    &tu.County,
                    &tu.Address,
                    &tu.InitFlag,
                    &tu.ShowMask,
                    &tu.FieldShowControl,
                    &tu.Label,
                    &tu.CanbeChat,
                    &tu.DutyID,
                    &tu.SecretLevel,
                    &tu.CreatedTime,
                    &tu.UpdatedTime,
                    &tu.UserSource,
    	}
}

// GetTUserColumns returns a TUserColumns struct with all column name mappings.
func GetTUserColumns () TUserColumns {
    return TUserColumns {
    		    ID: "id",
    		    UserID: "user_id",
    		    UserAccount: "user_account",
    		    UserName: "user_name",
    		    EnName: "en_name",
    		    Gender: "gender",
    		    Sign: "sign",
    		    Email: "email",
    		    Avatar: "avatar",
    		    Pwd: "pwd",
    		    Birth: "birth",
    		    Tel: "tel",
    		    UserDesc: "user_desc",
    		    Mobile: "mobile",
    		    UserStatus: "user_status",
    		    Nation: "nation",
    		    Province: "province",
    		    City: "city",
    		    County: "county",
    		    Address: "address",
    		    InitFlag: "init_flag",
    		    ShowMask: "show_mask",
    		    FieldShowControl: "field_show_control",
    		    Label: "label",
    		    CanbeChat: "canbe_chat",
    		    DutyID: "duty_id",
    		    SecretLevel: "secret_level",
    		    CreatedTime: "created_time",
    		    UpdatedTime: "updated_time",
    		    UserSource: "user_source",
    	}
}
// GetTUserByIDIndexFields returns the column names for index 't_user_id_pkey'.
func GetTUserByIDIndexFields() []string {
    return []string{ "id" }
}

// GetTUsersByMobileIndexFields returns the column names for index 't_user_mobile_index'.
func GetTUsersByMobileIndexFields() []string {
    return []string{ "mobile" }
}

// GetTUsersByUserNameEmailIndexFields returns the column names for index 't_user_user_name_email_index'.
func GetTUsersByUserNameEmailIndexFields() []string {
    return []string{ "user_name", "email" }
}

// GetTUserByUserIDIndexFields returns the column names for index 'unq_uid'.
func GetTUserByUserIDIndexFields() []string {
    return []string{ "user_id" }
}

