// Package iface contains the types for schema 'db_ccwork'.
package iface

// Code generated by xo. DO NOT EDIT.
import (
	"context"
    "github.com/UnderTreeTech/layout/internal/model"
)

// TUserIface is the aggregated interface for TUser DAO,
// embedding the base interface and all index-based interfaces.
type TUser interface {
    TUserBaseIface
    TUserByUserAccountIface
    TUserByUserIDIface
    TUsersByMobileIface
    TUsersByUserNameEmailIface
    TUserByIDIface
}

type TUserBaseIface interface {
    /********************Generate By XO: write method segment*********************/
    // AddTUser add the TUser to the database
    AddTUser(ctx context.Context, tu *model.TUser) (err error)

    // BatchTUser batch add TUser to the database
    BatchAddTUsers(ctx context.Context, list []*model.TUser) (err error)

    // EditTUser edit TUser in the database
    EditTUser(ctx context.Context, set map[string]interface{}, condition map[string]interface{}) (err error)

    // DeleteTUser delete TUser from the database
    DeleteTUser(ctx context.Context, condition map[string]interface{}) (err error)

    /********************Generate By XO: read method segment**********************/
    // FindTUser query one TUser by condition from the database
    FindTUser(ctx context.Context, condition map[string]interface{}) (res *model.TUser, err error)

    // FindTUsers all TUser by condition from the database
    FindTUsers(ctx context.Context, condition map[string]interface{}) (res []*model.TUser, err error)

    // CountTUser return count by condition from the database
    CountTUser(ctx context.Context, condition map[string]interface{}) (num int, err error)

    // BatchCountTUser groups records by groupKey and returns the count of each group.
    // The result is a slice of maps, where each map's key is the groupKey field value
    // and the value is the number of records in that group.
    // Example: groupKey="status" returns [{1: 10}, {2: 5}] meaning 10 records with status=1, 5 with status=2.
    BatchCountTUser(ctx context.Context, groupKey string, condition map[string]interface{}) (res []map[string]int, err error)
}


// TUserByIDIface defines the interface for TUser queries via index 't_user_id_pkey'.
// NOTE: embed this into the TUser DAO interface if needed, or add the method directly.
type TUserByIDIface interface {
    // FindTUserByID retrieves a row from 'db_ccwork.t_user'
    // via index 't_user_id_pkey'. Index fields: id.
    FindTUserByID(ctx context.Context, id uint) (res *model.TUser, err error)

    // EditTUserByID updates rows in 'db_ccwork.t_user'
    // via index 't_user_id_pkey'. Index fields: id.
    EditTUserByID(ctx context.Context, set map[string]interface{}, id uint) (err error)

    // DeleteTUserByID deletes rows from 'db_ccwork.t_user'
    // via index 't_user_id_pkey'. Index fields: id.
    DeleteTUserByID(ctx context.Context, id uint) (err error)
}


// TUsersByMobileIface defines the interface for TUser queries via index 't_user_mobile_index'.
// NOTE: embed this into the TUser DAO interface if needed, or add the method directly.
type TUsersByMobileIface interface {
    // FindTUsersByMobile retrieves rows from 'db_ccwork.t_user'
    // via index 't_user_mobile_index'. Index fields: mobile.
    FindTUsersByMobile(ctx context.Context, mobile string) (res []*model.TUser, err error)

    // EditTUsersByMobile updates rows in 'db_ccwork.t_user'
    // via index 't_user_mobile_index'. Index fields: mobile.
    EditTUsersByMobile(ctx context.Context, set map[string]interface{}, mobile string) (err error)

    // DeleteTUsersByMobile deletes rows from 'db_ccwork.t_user'
    // via index 't_user_mobile_index'. Index fields: mobile.
    DeleteTUsersByMobile(ctx context.Context, mobile string) (err error)
}


// TUsersByUserNameEmailIface defines the interface for TUser queries via index 't_user_user_name_email_index'.
// NOTE: embed this into the TUser DAO interface if needed, or add the method directly.
type TUsersByUserNameEmailIface interface {
    // FindTUsersByUserNameEmail retrieves rows from 'db_ccwork.t_user'
    // via index 't_user_user_name_email_index'. Index fields: user_name, email.
    FindTUsersByUserNameEmail(ctx context.Context, userName string, email string) (res []*model.TUser, err error)

    // EditTUsersByUserNameEmail updates rows in 'db_ccwork.t_user'
    // via index 't_user_user_name_email_index'. Index fields: user_name, email.
    EditTUsersByUserNameEmail(ctx context.Context, set map[string]interface{}, userName string, email string) (err error)

    // DeleteTUsersByUserNameEmail deletes rows from 'db_ccwork.t_user'
    // via index 't_user_user_name_email_index'. Index fields: user_name, email.
    DeleteTUsersByUserNameEmail(ctx context.Context, userName string, email string) (err error)
}


// TUserByUserAccountIface defines the interface for TUser queries via index 'unq_account'.
// NOTE: embed this into the TUser DAO interface if needed, or add the method directly.
type TUserByUserAccountIface interface {
    // FindTUserByUserAccount retrieves a row from 'db_ccwork.t_user'
    // via index 'unq_account'. Index fields: user_account.
    FindTUserByUserAccount(ctx context.Context, userAccount string) (res *model.TUser, err error)

    // EditTUserByUserAccount updates rows in 'db_ccwork.t_user'
    // via index 'unq_account'. Index fields: user_account.
    EditTUserByUserAccount(ctx context.Context, set map[string]interface{}, userAccount string) (err error)

    // DeleteTUserByUserAccount deletes rows from 'db_ccwork.t_user'
    // via index 'unq_account'. Index fields: user_account.
    DeleteTUserByUserAccount(ctx context.Context, userAccount string) (err error)
}


// TUserByUserIDIface defines the interface for TUser queries via index 'unq_uid'.
// NOTE: embed this into the TUser DAO interface if needed, or add the method directly.
type TUserByUserIDIface interface {
    // FindTUserByUserID retrieves a row from 'db_ccwork.t_user'
    // via index 'unq_uid'. Index fields: user_id.
    FindTUserByUserID(ctx context.Context, userID uint64) (res *model.TUser, err error)

    // EditTUserByUserID updates rows in 'db_ccwork.t_user'
    // via index 'unq_uid'. Index fields: user_id.
    EditTUserByUserID(ctx context.Context, set map[string]interface{}, userID uint64) (err error)

    // DeleteTUserByUserID deletes rows from 'db_ccwork.t_user'
    // via index 'unq_uid'. Index fields: user_id.
    DeleteTUserByUserID(ctx context.Context, userID uint64) (err error)
}
