// Package iface contains the types for schema db.
package iface

// Code generated by xo. DO NOT EDIT.
import (
	"context"
	"github.com/UnderTreeTech/layout/internal/model"
)

type TUser interface {
	/********************Generate By XO: write method segment*********************/
	// AddTUser add the TUser to the database
	AddTUser(ctx context.Context, tu *model.TUser) (err error)

	// BatchAddTUser batch add TUser to the database
	BatchAddTUsers(ctx context.Context, list []*model.TUser) (err error)

	// EditTUser edit TUser in the database
	EditTUser(ctx context.Context, setMap map[string]interface{}, condition map[string]interface{}) (err error)

	// DeleteTUser delete TUser from the database
	DeleteTUser(ctx context.Context, condition map[string]interface{}) (err error)

	/********************Generate By XO: read method segment**********************/
	// FindTUser query one TUser by condition from the database
	FindTUser(ctx context.Context, condition map[string]interface{}) (res *model.TUser, err error)

	// FindTUsers all TUser by condition from the database
	FindTUsers(ctx context.Context, condition map[string]interface{}) (res []*model.TUser, err error)

	// CountTUser return count by condition from the database
	CountTUser(ctx context.Context, condition map[string]interface{}) (num int, err error)

	// BatchCountTUser batch return count by condition from the database
	BatchCountTUser(ctx context.Context, groupKey string, condition map[string]interface{}) (res []map[string]int, err error)
}
