// Package dao contains the types for schema db.
package dao

// Code generated by xo. DO NOT EDIT.
import (
	"context"
	"errors"
	"fmt"
	"github.com/UnderTreeTech/layout/internal/model"

	"github.com/UnderTreeTech/layout/internal/utils/parser"

	"github.com/Masterminds/squirrel"
	"github.com/UnderTreeTech/waterdrop/pkg/database/sql"
	"github.com/UnderTreeTech/waterdrop/pkg/log"
)

/********************Generate By XO: write method segment*********************/
// AddTUser add the TUser to the database
func (d *dao) AddTUser(ctx context.Context, tu *model.TUser) (err error) {
	// sql insert query, primary key provided by autoincrement
	sqlStr, args, err := squirrel.
		Insert(model.GetTUserTableName()).
		Columns(model.GetTUserFieldStringSlice()...).
		Values(model.GetTUserAddField(tu)...).
		PlaceholderFormat(d.PlaceHolder()).
		ToSql()
	if err != nil {
		return
	}

	// parse sql to adapter databases
	sqlStr, err = parser.QuoteSQL(d.driver, sqlStr)
	if err != nil {
		return
	}

	// run query
	log.Debug(ctx, "AddTUser", log.String("sql", fmt.Sprint(sqlStr, args)))
	if tx, txErr := d.GetTxFromCtx(ctx); txErr != nil {
		_, err = d.db.Exec(ctx, sqlStr, args...)
	} else {
		_, err = tx.Exec(sqlStr, args...)
	}
	return
}

// BatchAddTUser batch add TUser to the database
func (d *dao) BatchAddTUsers(ctx context.Context, list []*model.TUser) (err error) {
	if 0 == len(list) {
		return
	}

	if 50 < len(list) {
		return errors.New("batch operation supports up to 50")
	}

	// sql insert query, primary key provided by autoincrement
	sqlBuilder := squirrel.
		Insert(model.GetTUserTableName()).
		Columns(model.GetTUserFieldStringSlice()...)

	for _, tu := range list {
		sqlBuilder = sqlBuilder.Values(model.GetTUserAddField(tu)...)
	}

	sqlStr, args, err := sqlBuilder.PlaceholderFormat(d.PlaceHolder()).ToSql()
	if err != nil {
		return err
	}

	// parse sql to adapter databases
	sqlStr, err = parser.QuoteSQL(d.driver, sqlStr)
	if err != nil {
		return
	}

	// run query
	log.Debug(ctx, "BatchAddTUsers", log.String("sql", fmt.Sprint(sqlStr, args)))
	if tx, txErr := d.GetTxFromCtx(ctx); txErr != nil {
		_, err = d.db.Exec(ctx, sqlStr, args...)
	} else {
		_, err = tx.Exec(sqlStr, args...)
	}
	return
}

// EditTUser edit TUser in the database
func (d *dao) EditTUser(ctx context.Context, setMap map[string]interface{}, condition map[string]interface{}) (err error) {
	// init build
	build := squirrel.Update(model.GetTUserTableName()).SetMap(setMap)

	// build sql
	build, err = d.AnalyticUpdate(build, condition)
	if err != nil {
		return
	}

	sqlStr, args, err := build.PlaceholderFormat(d.PlaceHolder()).ToSql()
	if err != nil {
		return
	}

	// parse sql to adapter databases
	sqlStr, err = parser.QuoteSQL(d.driver, sqlStr)
	if err != nil {
		return
	}

	// run query
	log.Debug(ctx, "EditTUser", log.String("sql", fmt.Sprint(sqlStr, args)))
	if tx, txErr := d.GetTxFromCtx(ctx); txErr != nil {
		_, err = d.db.Exec(ctx, sqlStr, args...)
	} else {
		_, err = tx.Exec(sqlStr, args...)
	}
	return
}

// DeleteTUser delete TUser from the database
func (d *dao) DeleteTUser(ctx context.Context, condition map[string]interface{}) (err error) {
	// init build
	build := squirrel.Delete(model.GetTUserTableName())

	// build sql
	build, err = d.AnalyticDelete(build, condition)
	if err != nil {
		return
	}

	sqlStr, args, err := build.PlaceholderFormat(d.PlaceHolder()).ToSql()
	if err != nil {
		return
	}

	// parse sql to adapter databases
	sqlStr, err = parser.QuoteSQL(d.driver, sqlStr)
	if err != nil {
		return
	}

	// run query
	log.Debug(ctx, "DeleteTUser", log.String("sql", fmt.Sprint(sqlStr, args)))
	if tx, txErr := d.GetTxFromCtx(ctx); txErr != nil {
		_, err = d.db.Exec(ctx, sqlStr, args...)
	} else {
		_, err = tx.Exec(sqlStr, args...)
	}
	return
}

/******************Generate By XO: read method segment**********************/
// FindTUser query one TUser by condition from the database
func (d *dao) FindTUser(ctx context.Context, condition map[string]interface{}) (res *model.TUser, err error) {
	// init build
	build := squirrel.Select(model.GetTUserFieldString()).From(model.GetTUserTableName())

	// forced master database query
	force := false
	if _, ok := condition["_force"]; ok {
		force = true
		delete(condition, "_force")
	}

	// build sql
	build, err = d.Analytic(build, condition)
	if err != nil {
		return
	}
	sqlStr, args, err := build.PlaceholderFormat(d.PlaceHolder()).ToSql()
	if err != nil {
		return
	}

	// parse sql to adapter databases
	sqlStr, err = parser.QuoteSQL(d.driver, sqlStr)
	if err != nil {
		return
	}

	// run query
	log.Debug(ctx, "FindTUser", log.String("sql", fmt.Sprint(sqlStr, args)))
	res = &model.TUser{}
	if tx, txErr := d.GetTxFromCtx(ctx); txErr != nil {
		if force {
			err = d.db.Master().QueryRow(ctx, sqlStr, args...).Scan(model.GetTUserScanField(res)...)
		} else {
			err = d.db.QueryRow(ctx, sqlStr, args...).Scan(model.GetTUserScanField(res)...)
		}
	} else {
		err = tx.QueryRow(sqlStr, args...).Scan(model.GetTUserScanField(res)...)
	}
	return
}

// FindTUsers all TUser by condition from the database
func (d *dao) FindTUsers(ctx context.Context, condition map[string]interface{}) (res []*model.TUser, err error) {
	// init build
	build := squirrel.Select(model.GetTUserFieldString()).From(model.GetTUserTableName())

	// forced master database query
	force := false
	if _, ok := condition["_force"]; ok {
		force = true
		delete(condition, "_force")
	}

	// build sql
	build, err = d.Analytic(build, condition)
	if err != nil {
		return
	}
	sqlStr, args, err := build.PlaceholderFormat(d.PlaceHolder()).ToSql()
	if err != nil {
		return
	}

	// parse sql to adapter databases
	sqlStr, err = parser.QuoteSQL(d.driver, sqlStr)
	if err != nil {
		return
	}

	// run query
	log.Debug(ctx, "FindTUsers", log.String("sql", fmt.Sprint(sqlStr, args)))
	var rows *sql.Rows
	if tx, txErr := d.GetTxFromCtx(ctx); txErr != nil {
		if force {
			rows, err = d.db.Master().Query(ctx, sqlStr, args...)
		} else {
			rows, err = d.db.Query(ctx, sqlStr, args...)
		}
	} else {
		rows, err = tx.Query(sqlStr, args...)
	}

	if err != nil {
		return
	}
	defer rows.Close()

	// load results
	res = make([]*model.TUser, 0)
	for rows.Next() {
		// scan rows
		tu := &model.TUser{}
		err = rows.Scan(model.GetTUserScanField(tu)...)
		if err != nil {
			return
		}

		res = append(res, tu)
	}
	return
}

// CountTUser return count by condition from the database
func (d *dao) CountTUser(ctx context.Context, condition map[string]interface{}) (num int, err error) {
	// init build
	build := squirrel.Select("count(*)").From(model.GetTUserTableName())

	// build sql
	build, err = d.Analytic(build, condition)
	if err != nil {
		return
	}

	sqlStr, args, err := build.Where(condition).PlaceholderFormat(d.PlaceHolder()).ToSql()
	if err != nil {
		return
	}

	// parse sql to adapter databases
	sqlStr, err = parser.QuoteSQL(d.driver, sqlStr)
	if err != nil {
		return
	}

	// run query
	log.Debug(ctx, "CountTUser", log.String("sql", fmt.Sprint(sqlStr, args)))
	if tx, txErr := d.GetTxFromCtx(ctx); txErr != nil {
		err = d.db.QueryRow(ctx, sqlStr, args...).Scan(&num)
	} else {
		err = tx.QueryRow(sqlStr, args...).Scan(&num)
	}
	return
}

// BatchCountTUser batch return count by condition from the database
func (d *dao) BatchCountTUser(ctx context.Context, groupKey string, condition map[string]interface{}) (res []map[string]int, err error) {
	// init build
	build := squirrel.Select("count(*) as num, " + groupKey).From(model.GetTUserTableName())

	// build sql
	build, err = d.Analytic(build, condition)
	if err != nil {
		return
	}

	sqlStr, args, err := build.Where(condition).GroupBy(groupKey).PlaceholderFormat(d.PlaceHolder()).ToSql()
	if err != nil {
		return
	}

	// parse sql to adapter databases
	sqlStr, err = parser.QuoteSQL(d.driver, sqlStr)
	if err != nil {
		return
	}

	// run query
	log.Debug(ctx, "BatchCountTUser", log.String("sql", fmt.Sprint(sqlStr, args)))
	var rows *sql.Rows
	if tx, txErr := d.GetTxFromCtx(ctx); txErr != nil {
		rows, err = d.db.Query(ctx, sqlStr, args...)
	} else {
		rows, err = tx.Query(sqlStr, args...)
	}
	if err != nil {
		return
	}
	defer rows.Close()

	// load results
	res = make([]map[string]int, 0)
	for rows.Next() {
		// scan rows
		var num int
		var groupValue string
		err = rows.Scan(&num, &groupValue)
		if err != nil {
			return
		}

		res = append(res, map[string]int{
			groupValue: num,
		})
	}
	return
}
