[server]
    [server.rpc]
        addr = "0.0.0.0:0"
        timeout = "1s"
        idleTimeout = "180s"
        maxLifeTime = "2h"
        forceCloseWait = "20s"
        keepAliveInterval = "60s"
        keepAliveTimeout = "20s"
        slowRequestDuration = "500ms"
        watchConfig = true
        enableMetric = true
    [server.http]
        addr = "0.0.0.0:20827"
        timeout = "2s"
        mode = "debug"
        slowRequestDuration = "500ms"
        watchConfig = true

[client]
    [client.rpc]
        [client.rpc.demo]
            key = "xHf74ZfV43cAUsUl"
            secret = "d0dbe915091d400bd8ee7f27f0791303"
            dialTimeout = "10s"
            block = false
            balancer = "round_robin"
            target = "etcd://default/service.demo.v1"
            timeout = "500ms"
            keepAliveInterval = "60s"
            keepAliveTimeout = "20s"
            slowRequestDuration = "500ms"

    [client.http]
        [client.http.app]
            hostURL = "http://localhost:20827"
            timeout = "1s"
            slowRequestDuration = "500ms"
            enableDebug = false
            enableSign = false
            key = "xHf74ZfV43cAUsUl"
            secret = "d0dbe915091d400bd8ee7f27f0791303"

[mysql]
    dbName = "test"
    driverName = "mysql"
    dsn = "root@tcp(127.0.0.1:3306)/test?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
    readDSN = ["root@tcp(127.0.0.1:3306)/test?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"]
    active = 20
    idle = 10
    idleTimeout ="4h"
    queryTimeout = "200ms"
    execTimeout = "300ms"
    tranTimeout = "400ms"
    slowQueryDuration = "250ms"

[mongo]
    dbName = "waterdrop"
    addr = "127.0.0.1:27017"
    dsn = "mongodb://root:123456@127.0.0.1:27017/?connect=direct"
    #specifies that maximum number of connections allowed in the driver's connection pool to each server.
    maxPoolSize = 100
    #specifies the minimum number of connections allowed in the driver's connection pool to each server. If
    minPoolSize = 50
    slowQueryDuration = "250ms"

[redis]
    dbName = "test"
    dbIndex = 0
    addr = ["127.0.0.1:6379"]
    deployMode = "node"
    minIdleConns = 5
    dialTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "10s"
    slowOpTimeout = "100ms"

[log]
    name = "run.log"
    dir = "."
    addCaller = true
    level = "debug"
    callerSkip = 1
    flushInterval= "1s"
    debug = true
    enableAsyncLog = false
    disableStacktrace = false
    maxSize = 500 # maximum 500M log size
    maxAge = 30 # retain maximum 30 days
    maxBackup = 100 # retian maximum 100 log
    watchConfig = true

[trace]
    [trace.jaeger]
        serviceName = "waterdrop"
        enableRPCMetrics = true
        #sampler config
        samplerType = "const"
        samplerParam = 1
        #report config
        agentAddr = "127.0.0.1:6831"
        reporterLogSpans = false
        reporterBufferFlushInterval = "2s"
        #option config
        maxTagValueLength = 5120

[etcd]
    prefix = "waterdrop"
    endpoints = ["127.0.0.1:2379"]
    dialTimeout = "1s"
    registerTTL = "90s"
    username = ""
    password = ""
